### PR TITLE
fix: search score (stars) no longer vertically

### PR DESCRIPTION
**Pull request by vrifox**
fix: search score (stars) no longer vertically

### CODE REVIEW

**Comment by vrifox** [comment]
Sorry, that was an unexpected result. :o

**Comment by razonyang** [comment]
Hi, could you please provide a screenshot? I have no intuitive feelings about this problem.

**Comment by vrifox** [comment]
I already thought about adding screenshots, but didn't know how. ^^
Here you go:

| **Before** | **After** |
| ------------- | ----------- |
| grafik | grafik |

**Comment by razonyang** [comment]
@vrifox Thanks, what browser do you use? I remember that I've tested it in Firefox and Chrome.

**Comment by vrifox** [comment]
I use Firefox 103.0.1

**Comment by vrifox** [comment]
Maybe it's a problem specific to [Natenoms Blog](https://blog.natenom.com/)? I don't know if the search implementation comes „officially“ with this theme or not.

**Review by razonyang — APPROVED** [review]

**Comment by razonyang** [comment]
It only happens in the case of very narrow width of screen. Let's keep it open, that blog seems missing palette(maybe a bug of theme).
image

**Comment by razonyang** [comment]
Oh, I found the problem, it's because the PurgeCSS remove the `text-nowrap` utilities, would you mind create another PR for this?

Just append the  `text-nowrap` to this line:
https://github.com/razonyang/hugo-theme-bootstrap/blob/2297bc6d8d5ee851fb75c4a96e1e63e112b17a52/purgecss.config.js#L30

**Comment by vrifox** [comment]
Thanks for approving. I will test it on my side. :)

**Comment by razonyang** [comment]
FYI @vrifox fixed by #652, that commit is credited to you.

**Comment by vrifox** [comment]
I wonder **how** you did that, but thanks anyway. :D

**Pull request closed without merging**
