### PR TITLE
feat: add the iframe shortcode and improve the game shortcode

### LINKED ISSUE #806: Extending the new game shortcode for data protection compliant embedding
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests

### Proposal

Instead of only for "games" your cool new shortcode could be used for data protection compliant embedding of OpenStreetMaps, umap, videos, etc. (?)

For this there should be two new parameters:
- button_text: Instead of just "Run Game"
- preload_description: A text (markdown allowed) that could include information about what would be loaded from where if you click on $button_text.

### Motivation and context

Data protection laws in Germany/Europe (and elsewhere?) forbid to load resources from third party websites without previous consent from your website visitors.

### PR DESCRIPTION
**Pull request by razonyang**
Fix #806

- [x] Add the `iframe` shortcode.
- [x] Add the `loadInfo` parameter for `game` shortcode.

### CODE REVIEW

**Comment by Rubonnek** [comment]
I've been looking through this patch and it seems better to remove the game shortcode in favor of the iframe shortcode since the latter is more generic.

**Comment by razonyang** [comment]
> It seems better to remove the game shortcode in favor of the iframe shortcode.

I thought about it, but I'm afraid there are someone else have used the `game` shortcode already. I prefer to leave the `game` shortcode, in order to avoid breaking changes.

**Comment by Natenom** [comment]
Works great. Thank you :)

**Comment by razonyang** [comment]
@Natenom Merged, could you do me a favor that translate the `load` in German?
https://github.com/razonyang/hugo-theme-bootstrap/blob/e18cf6efc9f72a5ad8e4e74c7dc4c139d8b40b66/i18n/en.toml#L163-L164

**Pull request merged**
