### PR TITLE
Redesign the UI

### PR DESCRIPTION
**Pull request by razonyang**
WIP

### CODE REVIEW

**Comment by vmihailenco** [comment]
Thanks for making the logo optional (at least it is missing at https://deploy-preview-215--hugo-theme-bootstrap.netlify.app/ :)

**Comment by razonyang** [comment]
> Thanks for making the logo optional (at least it is missing at https://deploy-preview-215--hugo-theme-bootstrap.netlify.app/ :)

The brand and logo were moved into the drawer. :)
image

> The top app bar displays the page title instead of the brand name.

But I'll make the logo optional later.

**Comment by vmihailenco** [comment]
Some feedback if you don't mind.

I think that moving navbar to a drawer is a step in wrong direction. I guess it makes sense on mobile devices, but on desktop it is just very strange and clumsy. I hope it is not a final decision...

Sample applies to a TOC. Most themes put it at the start of the post or in the right sidebar. It is hard to justify using a drawer...

**Comment by razonyang** [comment]
@vmihailenco I agree with you. I'll bring the navbar's previous style back later.

As for the TOC, I have no idea how to handle it now. I think we need to discuss it in details for deciding the right position and styles.

**Pull request merged**
