### PR TITLE
feat: Add gallery shortcode to create a Masonry with the Bootstrap grid system and cards component

### PR DESCRIPTION
**Pull request by costalfy**
Hi, 
I just add a new shortcode to create a gallery of images and use Masonry with the Bootstrap grid system and cards component as explained on https://getbootstrap.com/docs/5.1/examples/masonry/
I also add a tiny documentation page to use it

Thanks for this amazing theme

Regards

### CODE REVIEW

**Comment by razonyang** [comment]
Thanks for your contributions!

It seems that Masonry JS hasn't been imported yet. I'll clone your fork and play around with it, in order to make sure it works.

**Comment by costalfy** [comment]
Thanks 😊.  
I don't think JS is needed because it's already working on the sample page https://deploy-preview-481--hugo-theme-bootstrap.netlify.app/en/docs/shortcodes/gallery/

**Comment by razonyang** [comment]
> Thanks 😊. I don't think JS is needed because it's already working on the sample page https://deploy-preview-481--hugo-theme-bootstrap.netlify.app/en/docs/shortcodes/gallery/

It only works on images with same ratio, I'll handle the rest.

**Comment by razonyang** [comment]
I created another PR #483, since I didn't have access to push commit to your fork. The commits are still credited by you. 
Close this.

**Pull request closed without merging**
