### PR TITLE
feat: Initial RTL support

### PR DESCRIPTION
**Pull request by yshalsager**
https://github.com/razonyang/hugo-theme-bootstrap/issues/477

- Added a LanguageDirection variable, that is ltr by default, and rtl if the user set the language to be so.
`<html lang="{{ .Site.LanguageCode }}" dir="{{ default `ltr` .Language.LanguageDirection }}">`
- Updated some CSS properties in the theme to use logical properties to show stuff correctly for both of LTR and RTL.
- Made sure that fa-chevron-circle-down in posts navigation show in the correct directions using.
- Added an example page for RTL content, like markdown page in French example site.

### CODE REVIEW

**Comment by yshalsager** [comment]
image
RTL text in the codeblock is reversered

**Comment by yshalsager** [comment]
Bug: In main docs page, the aside docs-catalog is padded incorrectly.
image

**Comment by razonyang** [comment]
> RTL text in the codeblock is reversed

Hmm, I can't read it, could you please provide the expected text?

**Comment by razonyang** [comment]
BTW, I noticed that the setting panel shows up from the right, but the icon placed on the left, should we change it as well?

**Comment by yshalsager** [comment]
> > RTL text in the codeblock is reversed
> 
> Hmm, I can't read it, could you please provide the expected text?

It should be: `مستند HTML5`

**Comment by yshalsager** [comment]
> BTW, I noticed that the setting panel shows up from the right, but the icon placed on the left, should we change it as well?

It's nice-to-have, I'd say, but not a dealbreaker.

**Comment by razonyang** [comment]
Those issues won't be got fixed fast, I need to dig into the [RTLCSS](https://rtlcss.com/) first. I'll push commit to your fork later.

**Comment by yshalsager** [comment]
@razonyang Well, besides the reversed RTL text in codeblocks I would say everything is okay.

Take your time, and if there's anything I can help with feel free to tell :)

**Comment by razonyang** [comment]
I just created another PR #482, RTLCSS would be better than this approach(no need to convert CSS to RTL version manually). You can preview it on https://deploy-preview-482--hugo-theme-bootstrap.netlify.app/.

**Comment by yshalsager** [comment]
Closing in favor of https://github.com/razonyang/hugo-theme-bootstrap/pull/482

**Pull request closed without merging**
