### PR TITLE
style(post): update thumbnail style

### PR DESCRIPTION
**Pull request by razonyang**
I changed the style of thumbnail. There are two size thumbnails in each page now.
@chrisrummel @Natenom Please feel free to test it in your local environment. I'm looking forward to your feedback, because I'm not sure if it suits your request.

**Desktop**

The thumbnail is resized by fixed height `180px`.

image

**Mobile**

The thumbnail is resized by fixed height `120px`.

image

### CODE REVIEW

**Comment by Natenom** [comment]
The part with src set is nice, thank you for this :)

Why did you break with the featured image? I prefer the old style, because in my opinion the new style looks only good for photographs, not for Icons or screenshots AND you can't predict which part of the image will be "cropped". I think the old style was really nice. I tried to adapt your feature-thumbnail branch to achieve the old style, but it didn't work. As I said, I am a user, not a developer.

**Comment by razonyang** [comment]
@Natenom I changed back to the old style, it seems not need to create two thumbnails. Currently, both of Desktop and Mobile's are using the same thumbnail which resized with fixed height `120px`.

**Comment by razonyang** [comment]
> Normal view: image Mobile view: image
> 
> Why not using the old style? It was perfect :) 500px for mobile and 180 for normal view.

That's OK, I'll handle it later.

**Comment by Natenom** [comment]
Now it is perfect.

Thank you :)

**Pull request merged**
