### PR TITLE
update github pages workflow from planned deprecation of v3 to v4

### PR DESCRIPTION
**Pull request by liluzibird**

### CODE REVIEW

**Comment by liluzibird** [comment]
whaat why fail

**Comment by liluzibird** [comment]
bro wth

**Comment by liluzibird** [comment]
I just want to update the github deployment code, it can't be that hard wth

**Comment by liluzibird** [comment]
uploading the exact same code ^

**Comment by liluzibird** [comment]
Alright I guess it's my changes

**Comment by liluzibird** [comment]
guess I'll figure out what I'm doing wrong later

**Comment by razonyang** [comment]
> whaat why fail

That's because that it's a not a good idea to save code block inside a shortcode, since Hugo will execute it as a template, in this case `{{ runner* }}` will be treated as a Hugo function or variable, and then throw an error.

I've renamed it to be a page resource, update the [exampleSite/content/docs/deployment/github-pages/code/workflow](https://github.com/razonyang/hugo-theme-bootstrap/blob/master/exampleSite/content/docs/deployment/github-pages/code/workflow) will work.

Thanks for your contributions.

**Comment by liluzibird** [comment]
Ah ok, can't believe I didn't figure that out. I was so confused where to put the code I didn't even check that it was supposed to be in /docs/deployment/github-pages/code/workflow.

**Comment by razonyang** [comment]
> I was so confused where to put the code I didn't even check that it was supposed to be in /docs/deployment/github-pages/code/workflow.

You have modified the correct file, but the original file is not a good idea, and I created that file a few hours ago.
But I didn't change the workflow, please open another PR if you're still want to contribute.

**Pull request closed without merging**
