### PR TITLE
Thumbnail look up order

### PR DESCRIPTION
**Pull request by ElanHasson**
This change adds support for `Page.Params.Resources` lookups of image type by matching feature, cover, thumbnail in that priority.

The current implementation only supports `Page.Params.Images`, and this will be the default if it already exists to avoid breaking changes.

This is necessary due to the internal opengraph template not producing the correct url when using `Page.Params.Images`, only resources seem to work. See: https://github.com/gohugoio/hugo/blob/v0.92.0/tpl/tplimpl/embedded/templates/opengraph.html#L6-L17

I am new to Hugo, and I couldn't seem to figure out how to get the current `list-item.html` template to work AND the opengraph template using `.Page.Params.Images` without making my own template, so I am forced to change my partial `list-item.html`.

Please let me know if you're aware of a better way.

### CODE REVIEW

**Review by razonyang — APPROVED** [review]

**Comment by razonyang** [comment]
Thanks.

**Comment by ElanHasson** [comment]
Image viewer needs similar logic.

**Comment by razonyang** [comment]
> Image viewer needs similar logic.

Could you please describe it in detail?

**Comment by ElanHasson** [comment]
I'll try to reproduce  and send another issue/pr

**Pull request merged**
