### PR TITLE
Feature: add RTL support(RTLCSS)

### LINKED ISSUE #477: Support RTL languages natively
**Is your feature request related to a problem? Please describe.**
Out of the box, the theme doesn't support right to left languages like Arabic, Persian, and Hebrew.

To be able to use the theme for my personal website, both versions ([English](https://yshalsager.com/en/) and [Arabic](https://yshalsager.com/ar/)), I had to do some [CSS workarounds](https://github.com/yshalsager/personal_website/blob/master/assets/main/scss/_custom.scss) to make the theme work nicely with RTL content (still has many things that doesn't).

But I think having native compatibility with RTL would be a huge plus for our theme.

**Describe the solution you'd like**
Ideally, we can do the following:
- Add a `LanguageDirection` variable, that should be `ltr` by default, and `rtl` if the user set the language to be so.

```html
<html lang="{{ .Site.LanguageCode }}" dir="{{ default `ltr` .Language.LanguageDirection }}">
```
- Update some CSS properties in the theme to use logical properties to show stuff correctly for both of LTR and RTL like:
	- `margin/padding/border-right` to `margin/padding/border-inline-end`
	- `margin/padding/border-left` to `margin/padding/border-inline-start`
	- `left` to `inset-inline-start`
	- `right` to `inset-inline-end`
- Make fa-chevron-circle-down in posts navigation show in the correct directions.
- Make sure that codeblocks are kept LTR
- Add some example page for RTL content, like markdown page in French example site.

**Describe alternatives you've considered**
Some CSS that isn't nice at all [here](https://github.com/yshalsager/personal_website/blob/master/assets/main/scss/_custom.scss)

**Additional context**
I am ready to work on this or help with it if you prefer to work on it.
Inspired by https://github.com/CaiJimmy/hugo-theme-stack/pull/519 and https://github.com/adityatelange/hugo-PaperMod/pull/47

### PR DESCRIPTION
**Pull request by razonyang**
Fixed #477.

How to use it?

```shell
// install new dependencies
hugo mod npm pack
npm install

// preview
hugo server
```

### CODE REVIEW

**Comment by yshalsager** [comment]
Everything seems fine, except the reversed RTL in codeblock!

**Comment by razonyang** [comment]
> Everything seems fine, except the reversed RTL in codeblock!

I don't have an intuitive feeling about it, If there is a practical example to refer to, it will be better and help me understand.

**Comment by yshalsager** [comment]
> > Everything seems fine, except the reversed RTL in codeblock!
> 
> I don't have an intuitive feeling about it, If there is a practical example to refer to, it will be better and help me understand.

Sure!
Let's say I want to put the RTL text `تجربة نص` in HTML title tag in the following code:

It's two words `تجربة` that consists of four letters means experiment, and `نص` that means text.

```html
<!doctype html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="utf-8">
  <title>Add RTL here</title>
</head>
<body>
```

When it's shown correctly, it will be:

```html
  <title>تجربة نص</title>
```

When it's reversed, it's:

image

**Comment by razonyang** [comment]
@yshalsager Should it be rendered as what you input in the code block?

**Comment by razonyang** [comment]
@yshalsager I did some test with following code.

```html
<!doctype html>
<html lang="ar">
<head>
  <meta charset="utf-8">
  <title>Gopher, PHPer, Full Stack Engineer.</title>
</head>
<body>
</body>
</html>
```

The code block was rendered as expected. It may not an issue about CSS, I had no clue how to fix it now, please share your ideas if you have some.

image

**Comment by yshalsager** [comment]
> @yshalsager Should it be rendered as what you input in the code block? Please correct me if I misunderstand.

Yes, you're correct.

**Comment by yshalsager** [comment]
> @yshalsager I did some test with following code.
> 
> ```
> <!doctype html>
> <html lang="ar">
> <head>
>   <meta charset="utf-8">
>   <title>Gopher, PHPer, Full Stack Engineer.</title>
> </head>
> <body>
> </body>
> </html>
> ```
> 
> The code block was rendered as expected. It may not an issue about CSS, I had no clue how to fix it now, please share your ideas if you have some.
> 
> image

There's no issue with LTR text, so you can test with any RTL text.
Also, I have noticed that setting the `code` tag direction to RTL shows RTL text correctly but breaks the LTR with the same problem (text being reversed)

image

One final thing, I have noticed that PaperMod theme handles this correctly, so I am not sure where is the problem exactly, as I first thought it's related to the way hugo handles code blocks.

**Comment by yshalsager** [comment]
PaperMod
image

**Comment by razonyang** [comment]
@yshalsager Thanks for the example. I tested your sample on English demo site as well, the text seems always reversed. I believe that it is relative to Bootstrap. Sample as follows:

```html
<html lang="ar" dir="rtl">
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.rtl.min.css">
    </head>
    <body>
        <p>تجربة نص</p>
        <code class="hljs xml"><span class="hljs-meta">&lt;!doctype <span class="hljs-meta-keyword">html</span>&gt;</span>
            <span class="hljs-tag">&lt;<span class="hljs-name">html</span> <span class="hljs-attr">lang</span>=<span class="hljs-string">"ar"</span> <span class="hljs-attr">dir</span>=<span class="hljs-string">"rtl"</span>&gt;</span>
            <span class="hljs-tag">&lt;<span class="hljs-name">head</span>&gt;</span>
              <span class="hljs-tag">&lt;<span class="hljs-name">meta</span> <span class="hljs-attr">charset</span>=<span class="hljs-string">"utf-8"</span>&gt;</span>
              <span class="hljs-tag">&lt;<span class="hljs-name">title</span>&gt;</span>تجربة نص<span class="hljs-tag">&lt;/<span class="hljs-name">title</span>&gt;</span>
            <span class="hljs-tag">&lt;/<span class="hljs-name">head</span>&gt;</span>
            <span class="hljs-tag">&lt;<span class="hljs-name">body</span>&gt;</span>
        </code>
    </body>
</html>
```

The text was rendered as expected after removing Bootstrap CSS.

**Comment by yshalsager** [comment]
> @yshalsager Thanks for the example. I tested your sample on English demo site as well, the text seems always reversed. I believe that it is relative to Bootstrap. Sample as follows:
> 
> ```
> <html lang="ar" dir="rtl">
>     <head>
>         <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.rtl.min.css">
>     </head>
>     <body>
>         <p>تجربة نص</p>
>         <code class="hljs xml"><span class="hljs-meta">&lt;!doctype <span class="hljs-meta-keyword">html</span>&gt;</span>
>             <span class="hljs-tag">&lt;<span class="hljs-name">html</span> <span class="hljs-attr">lang</span>=<span class="hljs-string">"ar"</span> <span class="hljs-attr">dir</span>=<span class="hljs-string">"rtl"</span>&gt;</span>
>             <span class="hljs-tag">&lt;<span class="hljs-name">head</span>&gt;</span>
>               <span class="hljs-tag">&lt;<span class="hljs-name">meta</span> <span class="hljs-attr">charset</span>=<span class="hljs-string">"utf-8"</span>&gt;</span>
>               <span class="hljs-tag">&lt;<span class="hljs-name">title</span>&gt;</span>تجربة نص<span class="hljs-tag">&lt;/<span class="hljs-name">title</span>&gt;</span>
>             <span class="hljs-tag">&lt;/<span class="hljs-name">head</span>&gt;</span>
>             <span class="hljs-tag">&lt;<span class="hljs-name">body</span>&gt;</span>
>         </code>
>     </body>
> </html>
> ```
> 
> The text was rendered as expected after removing Bootstrap CSS.

You are correct, I was able to find https://github.com/twbs/bootstrap/issues/35219, which seems to resolved in v5.2.0 https://github.com/twbs/bootstrap/pull/35230

**Comment by razonyang** [comment]
I found out that is caused by the [`unicode-bidi`](https://developer.mozilla.org/en-US/docs/Web/CSS/unicode-bidi).

```scss
code {
    unicode-bidi: isolate;
}
```

**Comment by razonyang** [comment]
@yshalsager It should be fixed now, I'll merge into master later if everything is OK.

**Comment by yshalsager** [comment]
> @yshalsager It should be fixed now, I'll merge into master later if everything is OK.

@razonyang Awesome! Everything looks fine now.

I have tried the changes locally on my website and so far didn't notice anything broken except for bottom navigation arrows, which can be fixed with [this CSS](https://github.com/razonyang/hugo-theme-bootstrap/pull/479/files#diff-5353e89368ef50dd36e2ba3f0ace97963a2844ecd5de7ac84234990dea76e911R251), maybe there's a better way.

image

**Pull request merged**
