### PR TITLE
feat: look up modern formats for images with the same filename

### LINKED ISSUE #470: Add support for modern image formats (AVIF, JXL and WebP)
Support for modern image formats is a great way to improve the speed of a website.

The [Hugo Clarity](https://github.com/chipzoller/hugo-clarity) theme has a great way of dealing with new image formats like AVIF, JXL or WebP.

> If you reference an image such as sample.jpg in your post, Hugo Clarity will check to see if the same image (based on filename) exists in the modern formats of [WebP](https://en.wikipedia.org/wiki/WebP), [AVIF](https://en.wikipedia.org/wiki/AV1#AV1_Image_File_Format_(AVIF)) or [JXL](https://en.wikipedia.org/wiki/JPEG_XL). If it does, these will be presented to browsers as alternative options. Browsers that can support these formats will load them, while browsers that do not will fall-back to the default image.
>
> This process works for images with the file extensions jpg, jpeg, png, and gif.

Implemented this way would have no disadvantages even for old browsers that don't support modern image formats.

Then we can use [ImageMagick](https://github.com/ImageMagick/ImageMagick) to batch convert all JPG and PNG files in our image folder.

```
magick mogrify -format avif -depth 10 -define heic:speed=2 *.jpg

magick mogrify -format avif -depth 10 -define heic:speed=2 *.png
```

### PR DESCRIPTION
**Pull request by razonyang**
Close #470, it works only on the images placed on `static` folder.

### CODE REVIEW

**Comment by LITUATUI** [comment]
Thanks!

**Comment by LITUATUI** [comment]
Just a heads-up for people that want to batch convert their JPG and PNG images to the best image format today, AVIF.

Use [ImageMagick](https://github.com/ImageMagick/ImageMagick) to batch convert all JPG and PNG files in yout image folder.

In the terminal:
```
magick mogrify -format avif -depth 10 -define heic:speed=2 *.jpg

magick mogrify -format avif -depth 10 -define heic:speed=2 *.png
```

This will convert to AVIF in 10-bit.

**Comment by LITUATUI** [comment]
@razonyang this is working great for images inside the posts, but not for featured images in the front matter.

**Comment by razonyang** [comment]
@LITUATUI I missed the featured images totally, I'll fix it ASAP. As for the viewer, I don't think it's possible to detect which picture was used by the browser.

**Comment by razonyang** [comment]
@LITUATUI Fixed by latest commit.

**Pull request merged**
