### PR TITLE
feat: add support for Staticman comments

### PR DESCRIPTION
**Pull request by razonyang**
## TODOs

- [x] Nested comments
- [x] Avatar
- [x] URL, optional and configurable.
- [x] Make email optional and configurable, and display the default avatar if email is omitted.
- [x] Friendly notification messages.
- [x] Markdown Syntax, Emoji
- [x] Filter invalid content, such as `<script>` tag.
- [x] Sorting
- [x] Date format, something like `2 minutes ago`, extra JS are need. 
- [x] I18N
- [x] reCaptcha
- [x] Documentations
- [x] Pagination.
  - [x] Pagination page title.
- [x] Reset reCaptcha after submitting.

## Live Demo

English: https://razonyang.github.io/hugo-theme-bootstrap-staticman/blog/readme/#post-comments

Chinese: https://razonyang.github.io/hugo-theme-bootstrap-staticman/zh-hans/blog/readme/#post-comments

### Switch theme version

Use `feat-staticman` branch for testing.

### Update dependencies

```
$ hugo mod npm pack
$ npm update
```

Please check out the [documentation](https://deploy-preview-725--hbs-docs.netlify.app/en/docs/widgets/comments/#staticman) for details.

### CODE REVIEW

**Comment by Rubonnek** [comment]
Thank you for the quick turnaround!

[Staticman V3 API](https://github.com/eduardoboucas/staticman/blob/5d7ed7708775e3d4864382cca88d2d73ff875864/server.js#L73-L80) should be used instead to support Gitlab as well:

```diff
diff --git a/assets/js/staticman/client.ts b/assets/js/staticman/client.ts
index ceffe701..4ecd64b7 100644
--- a/assets/js/staticman/client.ts
+++ b/assets/js/staticman/client.ts
@@ -10,8 +10,9 @@ class Client
         const baseURL = params.staticman.baseurl.replace(/\/*$/, "")
         const repo = params.staticman.repo
         const branch = params.staticman.branch ? params.staticman.branch : 'master'
+        const service = params.staticman.service ? params.staticman.service : 'github'
         const property = params.staticman.property ? params.staticman.property : 'comments'
-        this.apiUrl = `${baseURL}/v2/entry/${repo}/${branch}/${property}`
+        this.apiUrl = `${baseURL}/v3/entry/${service}/${repo}/${branch}/${property}`
     }
```

The above patch will break the staticman client because it's firing an `OPTIONS` request here:

https://github.com/razonyang/hugo-theme-bootstrap/blob/458a2d14e4691336466c528329303df1364bddfd/assets/js/staticman/client.ts#L18-L23

I'm not sure why that is happening but when the request is sent, the request header of that JS above will look like the following:
```
OPTIONS /v2/entry/razonyang/hugo-bootstrap-theme-staticman/main/comments HTTP/1.1
Host: hbs-staticman.herokuapp.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Referer: https://razonyang.github.io/
Origin: https://razonyang.github.io
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
```

The staticman client should send a `POST` request that looks similar to the following (ignore the Content-Type below -- it can also be `application/json`):

```
POST /v3/entry/gitlab/burningrockgames/website-comments/main/comments HTTP/2
Host: brg-staticwoman-instance-2nm4reetiq-uc.a.run.app
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: http://localhost:1313/
Content-Type: application/x-www-form-urlencoded
Content-Length: 187
Origin: http://localhost:1313
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: cross-site
Sec-Fetch-User: ?1
TE: trailers
```

**Comment by razonyang** [comment]
@Rubonnek Thanks for the information, I've tried to use `v3` before but with no luck, I'll try to figure it out.

**Comment by Rubonnek** [comment]
@razonyang In my tests, I got the `v3` API to work using the following simple form:

```
<form method="POST" action="{{ .Site.Params.staticman.endpoint }}/v3/entry/{{ .Site.Params.staticman.service }}/{{ .Site.Params.staticman.username }}/{{ .Site.Params.staticman.repository }}/{{ .Site.Params.staticman.branch }}/{{ .Site.Params.staticman.toplevelproperty }}">
  <input name="options[redirect]" type="hidden" value="http://localhost:1313/">
  <!-- e.g. "2016-01-02-this-is-a-post" -->
  <!-- {{ $slug := replace $.RelPermalink "/" "" }} -->
  {{ $slug := replaceRE "/$" "" $.File.Dir }}
  <input name="options[slug]" type="hidden" value="{{ $slug }}">
  <label><input name="fields[name]" type="text">Name</label>
  <label><input name="fields[email]" type="text">E-mail</label>
  <label><textarea name="fields[message]"></textarea>Message</label>
  <button type="submit">Submit</button>
</form>
```

I think `options[redirect]` may be required. Not sure.

Also, the [staticwoman fork](https://github.com/hispanic/staticwoman) has much better error messages in some cases. It might be easier to debug using that fork.

**Comment by Rubonnek** [comment]
@razonyang I've found a possible solution for a proper Staticman v3 API client. Here's the patch:

```diff
diff --git a/assets/js/staticman/client.ts b/assets/js/staticman/client.ts
index fce7b8b5..81324e54 100644
--- a/assets/js/staticman/client.ts
+++ b/assets/js/staticman/client.ts
@@ -19,9 +19,9 @@ class Client
         return fetch(this.apiUrl, {
             method: 'POST',
             headers: {
-                'Content-Type': 'application/json'
+                'Content-Type': 'application/x-www-form-urlencoded'
             },
-            body: JSON.stringify(data),
+            body: data,
         }).then((response) => {
             return response.json();
         }).then((data) => {
diff --git a/assets/js/staticman/index.ts b/assets/js/staticman/index.ts
index 031840fc..d0ca6ce6 100644
--- a/assets/js/staticman/index.ts
+++ b/assets/js/staticman/index.ts
@@ -35,16 +35,12 @@ class Staticman implements Component
             button.setAttribute('disabled', 'true');
             
             const formData = new FormData(this.form)
-            const data = {
-                options: {
-                    slug: formData.get('slug'),
-                },
-                fields: {
-                    name: formData.get('name'),
-                    email: formData.get('email'),
-                    message: formData.get('message'),
-                },
-            }
+            const data = new URLSearchParams()
+            data.append("options[slug]", formData.get('slug'))
+            data.append("fields[name]", formData.get('name'))
+            data.append("fields[email]", formData.get('email'))
+            data.append("fields[message]", formData.get('message'))
+
             client.send(data).finally(() => {
                 this.lock = false;
                 button.removeAttribute('disabled');

```

Turns out that the if the `Content-Type` is not specified to be `application/x-www-form-urlencoded`, the Fetch API does not properly fire a `POST` request header. It instead uses the `OPTIONS` request due to some standards the Fetch API follows.

After fixing that, the JSON would be malformed as well for some reason. This is how Staticman would see it:
```
{
  '{"options":{"slug":"tools/my-new-tool/comments/en"},"fields":{"name":"test","email":"test@gmail.com","message":"test"}}': ''
}
```

I'm not sure why that's happening, so I just wrapped the data as `URLSearchParams` and now it shows up as expected:
```
{
  options: { slug: 'tools/my-new-tool/comments/en' },
  fields: { name: 'test', email: 'test@gmail.com', message: 'test' }
}
```

**Comment by razonyang** [comment]
@Rubonnek Thanks, it has been implemented 742d837ad3caca5cfa924d30db148897a6d99910, I just missed the `service` part of endpoint.

**Comment by Rubonnek** [comment]
@razonyang Oops, you made me realized it was my my staticman fork that didn't like the POST request because it's sitting behind a Google-configured server. No wonder lol.

**Pull request merged**
