### PR TITLE
Title Case implementation

### PR DESCRIPTION
**Pull request by Monklite**
`titleCase` is off by default. When on, all references to titles will be in titlecase.

Please note the following title references are having issues and are worth checking out:  

- `breadcrumbs.html` is having problems for whatever reason, it was super wonky to work with this. It looks like it keeps returning nil for `.Site.Params.titleCase` for whatever reason.
- `search.html` has not been modified. I tried to mess with this and getting it implemented was odd. Hopefully by looking at this PR, you can see how it all works, I'm sure you can fix the two mentioned issues no problem.

### CODE REVIEW

**Review by razonyang — APPROVED** [review]

**Comment by razonyang** [comment]
Thanks for your contributions.

**Comment by Monklite** [comment]
No problem. I can test your revisions if you want. Now it's just figuring out the search issue as it looks like you figured out the breadcrumbs issue.

**Comment by razonyang** [comment]
Yep. I think the search and breadcrumb problems have been fixed.
Please feel free to test and share your feedback.

**Comment by Monklite** [comment]
Seems good so far, stellar work. Really appreciate it!

**Pull request merged**
