### PR TITLE
feat: add the post.plainifyExcerpt parameter

### PR DESCRIPTION
**Pull request by razonyang**

### CODE REVIEW

**Comment by chrisrummel** [comment]
Yes, this seems to successfully fix the behaviour described in [issue #346](https://github.com/razonyang/hugo-theme-bootstrap/issues/346).

**Comment by razonyang** [comment]
> Yes, this seems to successfully fix the behaviour described in [issue #346](https://github.com/razonyang/hugo-theme-bootstrap/issues/346).

Thank you for quickly testing this patch, I'll merge it later if it is OK.

**Comment by chrisrummel** [comment]
> Yes, this seems to successfully fix the behaviour described in [issue #346](https://github.com/razonyang/hugo-theme-bootstrap/issues/346).

No, wait, there are still unrendered htmlspecialchars. (You know where to look, e.g. 2nd post.)

**Comment by razonyang** [comment]
> > Yes, this seems to successfully fix the behaviour described in [issue #346](https://github.com/razonyang/hugo-theme-bootstrap/issues/346).
> 
> No, wait, there are still unrendered htmlspecialchars. (You know where to look, e.g. 2nd post.)

Could you please provide the source content of that post? It looks strange.

**Comment by chrisrummel** [comment]
You can have a look at it in my repository:
https://github.com/chrisrummel/bronski.net/blob/main/content/2022/20220106-muschel/index.md
https://github.com/chrisrummel/bronski.net/blob/main/content/2021/20211216-staub/index.md

In the first it is simple double straight quotes (not typographically ones) and in the second it is a triple-dot that is turned into an ellipsis by the render engine.

**Comment by chrisrummel** [comment]
Alright, the `` htmlUnescape `` seems to do the job.
Thanks a lot! Sadly I don't know every hugo function, so I can do quite a bit on my own, but not everything. Thanks again.

**Comment by razonyang** [comment]
@chrisrummel Thanks for your source content, you can remove me from your repository.

**Pull request merged**
